services:
  - type: web
    name: outlook-email-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: HEADLESS
        value: "true"
      - key: PORT
        sync: false
    
    healthCheckPath: /ping
